Contact form
riskmaris/Contact-Form pull request #3
Opened 2023-04-04 09:14 UTC by riskmaris

# Setup and mobile-first
Added 2 different background images for the contact form section.
Added style for the title of the contact form
Added style for input fields

2023-04-04 20:51 UTC, franclobo reviewed
Hi @riskmaris, @hagan23, and @rahimialijan, 

![roja](https://user-images.githubusercontent.com/58642949/229917793-ddd41eb1-077c-4508-abfa-3da34543cb1f.jpg)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a professional README file. Please 🙏🏽 add the information of all members in the Authors section.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-05 06:46 UTC, Shedrack-Sunday requested changes
Hi @riskmaris           👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done well implementing the requirements,  However, there are a few you need to work on, to move to the next project. 💯

 
![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights
✔️ Good PR summary
✔️ Nice code implementation
  
# Required Changes ♻️

- [x] Your form is not submitting properly, because it lacks an `ID`. I've given a detailed explanation of this below 👍 
- There's a bit of styling that needs to be an adjustment 


_check the comment section for a detailed review_ 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-04-05 06:46 UTC, Shedrack-Sunday commented on index.html
> +                <form action="https://formspree.io/f/{form_id}" method="post" class="labels">
- [ ] You need to add the `id` to the formspree to make it submit successfully. use this [Link](https://formspree.io/html/) to see the process of how to do so 👍 
- Also capitalize the `POST` method to make it a standard highlight understandable to all 👍

2023-04-05 06:46 UTC, Shedrack-Sunday commented on index.html
> +                    <textarea name="message" id="message" cols="30" rows="10" placeholder="message" required></textarea>
- [ ] Name input should have a `maxlength="30"` attribute.
- [ ] The  Message input should have a  `maxlength="500"` attribute.
- This is right to give proper validations 👍

2023-04-05 06:46 UTC, Shedrack-Sunday commented on index.html
> +                <form action="https://formspree.io/f/{form_id}" method="post" class="labels">
- [ ] The padding on the forms needs a little bit of adjustment. It does not give a nice UI to have text starting on the margin attached.

## View 👍 
![image](https://user-images.githubusercontent.com/50990925/230001782-40166132-3da1-4a83-9e1f-b3fa6a333619.png)

## Figma:
![image](https://user-images.githubusercontent.com/50990925/230002043-51ecc53c-763a-4e34-8452-3979d1f0f190.png)

2023-04-05 08:02 UTC, christianbiring1 requested changes
Hi @riskmaris , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
# STATUS: REQUEST CHANGES :recycle: 
![soclose](https://user-images.githubusercontent.com/97100091/230019253-25e9cdd8-f945-4de0-8ce5-e9df1cbcb5d3.gif)


 ## Highlights
- [ ] The form spree service has been used correctly :+1: 
- [ ] Descriptive PR `title` and `summary` :+1: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-05 12:25 UTC, AbayomiOlaoye approved these changes
Hi @Team :wave:, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![applause](https://user-images.githubusercontent.com/99715640/213818870-485b6c36-1d87-4b93-9a0c-ce2ae86d9a9d.gif)

## Highlights
- Great implementation of reviewer's suggestions :heavy_check_mark: 
- Textarea has max-length :heavy_check_mark: 
- Good UI implementation :heavy_check_mark: 
- Linter checks are passing :heavy_check_mark: 
- Professional ReadMe documentation :heavy_check_mark: 

## Optional suggestions

_N/A_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-06 07:35 UTC, merged